[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.28.0"

[programs.localnet]
transfer_fee_collector = "G6rJUiBCRzoTy1VNskvqxNr9zTkKoBScqnNLHbwtKdBz"

[programs.devnet]
transfer_fee_collector = "G6rJUiBCRzoTy1VNskvqxNr9zTkKoBScqnNLHbwtKdBz"

[programs.mainnet]
transfer_fee_collector = "G6rJUiBCRzoTy1VNskvqxNr9zTkKoBScqnNLHbwtKdBz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 